apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-pod
spec:
  containers:
  - name: ubuntu
    image: ubuntu:latest
    command: ["sleep", "infinity"]
  imagePullSecrets:
  - name: my-image-pull-secret
  serviceAccountName: my-service-account
